name: apply formatting for rust and check for compilation

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  compile:
    runs-on: codeberg-tiny
    if: ${{ startsWith(github.head_ref, 'all/') || startsWith(github.head_ref, 'server/') }}
    timeout-minutes: 5
    container:
      image: guillaumematton/cicd-zappy:20260601.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Build
        run: make zappy_server

      - name: Install Clippy
        run: rustup component add clippy

      - name: Clippy
        run: |
          cd server
          cargo clippy --all-targets --all-features -- -D warnings

  Apply-formatting:
    runs-on: codeberg-tiny
    if: ${{ startsWith(github.head_ref, 'all/') || startsWith(github.head_ref, 'server/') }}
    timeout-minutes: 5
    container:
      image: guillaumematton/cicd-zappy:20260601.2
    steps:
      - name: Set safe directory
        run: git config --global --add safe.directory $FORGEJO_REPOSITORY

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}
      
      - name: Apply fmt
        run: |
          cd server
          cargo fmt --all

      - name: Commit and push formatting changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No formatting changes to commit."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "style: apply cargo fmt"
          git push
